import { Comment } from "./Comment.ts";

export const getGeneratedComments = (): Array<Comment> => [
  {
    id: 116,
    sender: "yrymtg",
    message: "3ecftj",
    parent: 76,
    rate: 3,
    rated: null,
  },
  {
    id: 68,
    sender: "8rwx3",
    message: "fuzk5",
    parent: null,
    rate: 83,
    rated: null,
  },
  {
    id: 72,
    sender: "esq39",
    message: "giups",
    parent: 17,
    rate: 74,
    rated: null,
  },
  {
    id: 8,
    sender: "a48c",
    message: "w3xxq",
    parent: null,
    rate: 33,
    rated: null,
  },
  {
    id: 88,
    sender: "xxh9s",
    message: "n3lwp",
    parent: null,
    rate: 30,
    rated: null,
  },
  {
    id: 69,
    sender: "b6pxw",
    message: "osoyv",
    parent: 14,
    rate: 1,
    rated: null,
  },
  {
    id: 95,
    sender: "zgmt2",
    message: "wo66i",
    parent: null,
    rate: 77,
    rated: null,
  },
  {
    id: 87,
    sender: "s0q55",
    message: "b33dc",
    parent: null,
    rate: 48,
    rated: null,
  },
  {
    id: 56,
    sender: "xk15n",
    message: "dqcy1k",
    parent: 5,
    rate: 93,
    rated: null,
  },
  {
    id: 128,
    sender: "iq21w",
    message: "h8dpb",
    parent: 59,
    rate: 24,
    rated: null,
  },
  {
    id: 84,
    sender: "h7244",
    message: "j7nyt",
    parent: null,
    rate: 15,
    rated: null,
  },
  {
    id: 96,
    sender: "7t11yf",
    message: "u9k27",
    parent: null,
    rate: 50,
    rated: null,
  },
  {
    id: 64,
    sender: "m8i5t",
    message: "xtjcc",
    parent: 62,
    rate: 98,
    rated: null,
  },
  {
    id: 33,
    sender: "lc3zl",
    message: "zm0ez",
    parent: null,
    rate: 66,
    rated: null,
  },
  {
    id: 113,
    sender: "u04si",
    message: "weq8a",
    parent: 108,
    rate: 66,
    rated: null,
  },
  {
    id: 104,
    sender: "j7si1",
    message: "iatzm",
    parent: 6,
    rate: 24,
    rated: null,
  },
  {
    id: 60,
    sender: "2pfor",
    message: "ds3mo",
    parent: 55,
    rate: 93,
    rated: null,
  },
  {
    id: 34,
    sender: "l4n11",
    message: "saauq",
    parent: null,
    rate: 87,
    rated: null,
  },
  {
    id: 115,
    sender: "wqcta",
    message: "dqaac",
    parent: null,
    rate: 58,
    rated: null,
  },
  {
    id: 124,
    sender: "cctuz",
    message: "yui9d",
    parent: null,
    rate: 89,
    rated: null,
  },
  {
    id: 13,
    sender: "lpig0k",
    message: "egco7",
    parent: null,
    rate: 68,
    rated: null,
  },
  {
    id: 75,
    sender: "nusli",
    message: "dtn1",
    parent: 69,
    rate: 69,
    rated: null,
  },
  {
    id: 112,
    sender: "ockmug",
    message: "47mwe",
    parent: null,
    rate: 67,
    rated: null,
  },
  {
    id: 43,
    sender: "51pi1",
    message: "lcw72",
    parent: null,
    rate: 43,
    rated: null,
  },
  {
    id: 117,
    sender: "xdn0d",
    message: "2k9gq",
    parent: null,
    rate: 50,
    rated: null,
  },
  {
    id: 3,
    sender: "oo06q",
    message: "48a6m",
    parent: null,
    rate: 3,
    rated: null,
  },
  {
    id: 67,
    sender: "8m5a7",
    message: "z2o0z",
    parent: null,
    rate: 68,
    rated: null,
  },
  {
    id: 18,
    sender: "49htb",
    message: "dxaqp",
    parent: null,
    rate: 31,
    rated: null,
  },
  {
    id: 102,
    sender: "htphu",
    message: "ww8eo",
    parent: null,
    rate: 78,
    rated: null,
  },
  {
    id: 103,
    sender: "42l5n",
    message: "vveq1",
    parent: null,
    rate: 7,
    rated: null,
  },
  {
    id: 73,
    sender: "besbn",
    message: "m7g11",
    parent: null,
    rate: 71,
    rated: null,
  },
  {
    id: 61,
    sender: "qxo9ll",
    message: "ut1wg",
    parent: null,
    rate: 69,
    rated: null,
  },
  {
    id: 35,
    sender: "yq6ing",
    message: "017kgk",
    parent: null,
    rate: 2,
    rated: null,
  },
  {
    id: 100,
    sender: "1xa2s",
    message: "gh30x",
    parent: null,
    rate: 93,
    rated: null,
  },
  {
    id: 55,
    sender: "3f8i8",
    message: "9yys8",
    parent: null,
    rate: 61,
    rated: null,
  },
  {
    id: 2,
    sender: "q2r49",
    message: "y94mah",
    parent: null,
    rate: 29,
    rated: null,
  },
  {
    id: 99,
    sender: "z9iyl",
    message: "yi7aeg",
    parent: 66,
    rate: 67,
    rated: null,
  },
  {
    id: 98,
    sender: "8u7z4",
    message: "ntrku",
    parent: null,
    rate: 27,
    rated: null,
  },
  {
    id: 44,
    sender: "zcp4q",
    message: "yxzir",
    parent: 41,
    rate: 79,
    rated: null,
  },
  {
    id: 114,
    sender: "2ixr",
    message: "t98jg",
    parent: null,
    rate: 91,
    rated: null,
  },
  {
    id: 81,
    sender: "paz5c",
    message: "gkppo",
    parent: null,
    rate: 77,
    rated: null,
  },
  {
    id: 14,
    sender: "5aw41",
    message: "tdph6",
    parent: null,
    rate: 7,
    rated: null,
  },
  {
    id: 109,
    sender: "qkm8w",
    message: "41l5",
    parent: null,
    rate: 64,
    rated: null,
  },
  {
    id: 62,
    sender: "3yb82k",
    message: "dlzw7",
    parent: null,
    rate: 20,
    rated: null,
  },
  {
    id: 50,
    sender: "mvnyr",
    message: "kb45u",
    parent: 40,
    rate: 78,
    rated: null,
  },
  {
    id: 15,
    sender: "7ss0a",
    message: "e0m2ni",
    parent: null,
    rate: 20,
    rated: null,
  },
  {
    id: 126,
    sender: "6ql4c",
    message: "cqgov",
    parent: null,
    rate: 86,
    rated: null,
  },
  {
    id: 45,
    sender: "hlai5",
    message: "4w4yl",
    parent: null,
    rate: 26,
    rated: null,
  },
  {
    id: 23,
    sender: "ol0xk",
    message: "ecwy8",
    parent: null,
    rate: 3,
    rated: null,
  },
  {
    id: 20,
    sender: "8bzj0k",
    message: "va9nr",
    parent: 7,
    rate: 50,
    rated: null,
  },
  {
    id: 70,
    sender: "8076l",
    message: "pcu12f",
    parent: null,
    rate: 25,
    rated: null,
  },
  {
    id: 89,
    sender: "rkkfk",
    message: "cvrne",
    parent: null,
    rate: 12,
    rated: null,
  },
  {
    id: 118,
    sender: "qtxq4",
    message: "bk2vf",
    parent: 17,
    rate: 18,
    rated: null,
  },
  {
    id: 25,
    sender: "xmu2u",
    message: "m6u9s",
    parent: 16,
    rate: 30,
    rated: null,
  },
  {
    id: 86,
    sender: "ql5wn",
    message: "qm7nok",
    parent: null,
    rate: 82,
    rated: null,
  },
  {
    id: 51,
    sender: "yrr3l",
    message: "bvelv",
    parent: null,
    rate: 19,
    rated: null,
  },
  {
    id: 101,
    sender: "oma9z",
    message: "s1qve",
    parent: 4,
    rate: 66,
    rated: null,
  },
  {
    id: 59,
    sender: "6j8bd",
    message: "wpg0w",
    parent: null,
    rate: 56,
    rated: null,
  },
  {
    id: 6,
    sender: "qrulf",
    message: "1u38si",
    parent: 1,
    rate: 34,
    rated: null,
  },
  {
    id: 46,
    sender: "2671fi",
    message: "harqg",
    parent: null,
    rate: 80,
    rated: null,
  },
  {
    id: 90,
    sender: "t3ziq",
    message: "479xh",
    parent: null,
    rate: 18,
    rated: null,
  },
  {
    id: 106,
    sender: "eol53",
    message: "nvo7e",
    parent: null,
    rate: 45,
    rated: null,
  },
  {
    id: 83,
    sender: "hl85d",
    message: "zuq2k",
    parent: null,
    rate: 54,
    rated: null,
  },
  {
    id: 4,
    sender: "41m4u",
    message: "fh5e1",
    parent: null,
    rate: 17,
    rated: null,
  },
  {
    id: 66,
    sender: "rzntdj",
    message: "8aplt",
    parent: null,
    rate: 30,
    rated: null,
  },
  {
    id: 119,
    sender: "0vfcr",
    message: "k1qi2",
    parent: null,
    rate: 25,
    rated: null,
  },
  {
    id: 120,
    sender: "3y1oqk",
    message: "zedwa",
    parent: null,
    rate: 60,
    rated: null,
  },
  {
    id: 111,
    sender: "c68gh",
    message: "difik",
    parent: 12,
    rate: 37,
    rated: null,
  },
  {
    id: 123,
    sender: "f51qs",
    message: "hbnz2",
    parent: null,
    rate: 3,
    rated: null,
  },
  {
    id: 27,
    sender: "wnzhp",
    message: "qpn1yg",
    parent: null,
    rate: 97,
    rated: null,
  },
  {
    id: 5,
    sender: "pdj4f",
    message: "cmsoni",
    parent: null,
    rate: 55,
    rated: null,
  },
  {
    id: 16,
    sender: "0f9dx",
    message: "0mrul",
    parent: null,
    rate: 65,
    rated: null,
  },
  {
    id: 94,
    sender: "b28ng",
    message: "e4a47",
    parent: null,
    rate: 73,
    rated: null,
  },
  {
    id: 49,
    sender: "7t629",
    message: "z9jkt",
    parent: null,
    rate: 45,
    rated: null,
  },
  {
    id: 57,
    sender: "n8rbj",
    message: "79t5l",
    parent: 26,
    rate: 66,
    rated: null,
  },
  {
    id: 74,
    sender: "gc3gh",
    message: "cr1twj",
    parent: 37,
    rate: 2,
    rated: null,
  },
  {
    id: 24,
    sender: "kpuxv",
    message: "kbdaz",
    parent: null,
    rate: 19,
    rated: null,
  },
  {
    id: 9,
    sender: "8cejdg",
    message: "lhojr",
    parent: 8,
    rate: 57,
    rated: null,
  },
  {
    id: 21,
    sender: "kf5cv",
    message: "q5asv",
    parent: 20,
    rate: 47,
    rated: null,
  },
  {
    id: 125,
    sender: "3ipkgk",
    message: "f6kjb",
    parent: null,
    rate: 79,
    rated: null,
  },
  {
    id: 31,
    sender: "xfkoa",
    message: "pxypl",
    parent: 18,
    rate: 27,
    rated: null,
  },
  {
    id: 48,
    sender: "a7p0ul",
    message: "zh47v",
    parent: null,
    rate: 14,
    rated: null,
  },
  {
    id: 58,
    sender: "nat2qk",
    message: "88b7y",
    parent: null,
    rate: 38,
    rated: null,
  },
  {
    id: 28,
    sender: "4i1hb",
    message: "xodr",
    parent: null,
    rate: 83,
    rated: null,
  },
  {
    id: 26,
    sender: "ktwzm",
    message: "i31co",
    parent: 5,
    rate: 21,
    rated: null,
  },
  {
    id: 1,
    sender: "v8afy",
    message: "umkcti",
    parent: null,
    rate: 40,
    rated: null,
  },
  {
    id: 41,
    sender: "j2plc",
    message: "cniqi",
    parent: null,
    rate: 100,
    rated: null,
  },
  {
    id: 19,
    sender: "1u7l3",
    message: "d5x6x",
    parent: 13,
    rate: 58,
    rated: null,
  },
  {
    id: 40,
    sender: "g3fpn",
    message: "nqag7",
    parent: 18,
    rate: 100,
    rated: null,
  },
  {
    id: 54,
    sender: "s7t2v",
    message: "e309o",
    parent: null,
    rate: 29,
    rated: null,
  },
  {
    id: 22,
    sender: "i3pka",
    message: "cfqxd",
    parent: 11,
    rate: 84,
    rated: null,
  },
  {
    id: 30,
    sender: "bfloyh",
    message: "rt9sa",
    parent: null,
    rate: 36,
    rated: null,
  },
  {
    id: 63,
    sender: "288ck",
    message: "1z4vy",
    parent: null,
    rate: 63,
    rated: null,
  },
  {
    id: 42,
    sender: "0ikd7",
    message: "2drv2",
    parent: null,
    rate: 99,
    rated: null,
  },
  {
    id: 32,
    sender: "0yudng",
    message: "z634g",
    parent: null,
    rate: 80,
    rated: null,
  },
  {
    id: 36,
    sender: "c5vz7",
    message: "x6fem",
    parent: null,
    rate: 44,
    rated: null,
  },
  {
    id: 37,
    sender: "9rt7q",
    message: "lbu7y",
    parent: null,
    rate: 2,
    rated: null,
  },
  {
    id: 38,
    sender: "875b8",
    message: "5ymkyh",
    parent: null,
    rate: 72,
    rated: null,
  },
  {
    id: 7,
    sender: "ug9xs",
    message: "fq370i",
    parent: null,
    rate: 46,
    rated: null,
  },
  {
    id: 39,
    sender: "96mgc",
    message: "wsrj3",
    parent: null,
    rate: 100,
    rated: null,
  },
  {
    id: 10,
    sender: "hj99u",
    message: "4dduq",
    parent: 4,
    rate: 9,
    rated: null,
  },
  {
    id: 77,
    sender: "q1rqn",
    message: "1bis2",
    parent: null,
    rate: 87,
    rated: null,
  },
  {
    id: 47,
    sender: "8txm",
    message: "suo6gg",
    parent: 42,
    rate: 35,
    rated: null,
  },
  {
    id: 91,
    sender: "goz35",
    message: "5d2v1",
    parent: null,
    rate: 75,
    rated: null,
  },
  {
    id: 53,
    sender: "i9p0w",
    message: "9510g",
    parent: null,
    rate: 2,
    rated: null,
  },
  {
    id: 110,
    sender: "tx2x5",
    message: "faumt",
    parent: null,
    rate: 92,
    rated: null,
  },
  {
    id: 97,
    sender: "2wv4gj",
    message: "ug4k8",
    parent: 35,
    rate: 65,
    rated: null,
  },
  {
    id: 80,
    sender: "w2ga6",
    message: "gpk0h",
    parent: null,
    rate: 89,
    rated: null,
  },
  {
    id: 108,
    sender: "p0r3f",
    message: "yygxv",
    parent: null,
    rate: 66,
    rated: null,
  },
  {
    id: 105,
    sender: "0w9u",
    message: "bg7ov",
    parent: null,
    rate: 76,
    rated: null,
  },
  {
    id: 12,
    sender: "tmptq",
    message: "mo5w7k",
    parent: null,
    rate: 20,
    rated: null,
  },
  {
    id: 11,
    sender: "fh4p4",
    message: "l73to",
    parent: 10,
    rate: 6,
    rated: null,
  },
  {
    id: 71,
    sender: "5uscw",
    message: "bjjw1",
    parent: null,
    rate: 1,
    rated: null,
  },
  {
    id: 122,
    sender: "ituh6",
    message: "9r4yy",
    parent: 32,
    rate: 15,
    rated: null,
  },
  {
    id: 17,
    sender: "2dezol",
    message: "lwgjj",
    parent: null,
    rate: 56,
    rated: null,
  },
  {
    id: 52,
    sender: "sv99p",
    message: "njubp",
    parent: null,
    rate: 30,
    rated: null,
  },
  {
    id: 93,
    sender: "xuirwg",
    message: "d7qa4j",
    parent: 30,
    rate: 83,
    rated: null,
  },
  {
    id: 76,
    sender: "qy97i",
    message: "3r51v",
    parent: null,
    rate: 49,
    rated: null,
  },
  {
    id: 65,
    sender: "jtpjc",
    message: "j4emj",
    parent: null,
    rate: 23,
    rated: null,
  },
  {
    id: 121,
    sender: "n3947",
    message: "tdhss",
    parent: null,
    rate: 50,
    rated: null,
  },
  {
    id: 78,
    sender: "5m73r",
    message: "tg1ir",
    parent: 62,
    rate: 62,
    rated: null,
  },
  {
    id: 85,
    sender: "z8it",
    message: "pgab4",
    parent: null,
    rate: 98,
    rated: null,
  },
  {
    id: 82,
    sender: "ucubo",
    message: "0x9qm",
    parent: null,
    rate: 76,
    rated: null,
  },
  {
    id: 79,
    sender: "1c1u8",
    message: "qrsp2",
    parent: null,
    rate: 53,
    rated: null,
  },
  {
    id: 107,
    sender: "1vj7ag",
    message: "lqxcuj",
    parent: null,
    rate: 26,
    rated: null,
  },
  {
    id: 92,
    sender: "8pjnt",
    message: "vlr9s",
    parent: null,
    rate: 62,
    rated: null,
  },
  {
    id: 127,
    sender: "2j1",
    message: "pe1cx",
    parent: null,
    rate: 6,
    rated: null,
  },
  {
    id: 29,
    sender: "3rke3",
    message: "fh6wxk",
    parent: 27,
    rate: 72,
    rated: null,
  },
];
